IQ_Test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('iq.urls')),
]

iq/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home, iq_test
from django.views.generic import TemplateView


urlpatterns = [
    path('', home, name='home'),
    path('test/', iq_test, name='test'),
    path('result/', TemplateView.as_view(template_name='result.html'), name='result'),
]

iq/models.py
from django.db import models


# Create your models here.

class Question_sets(models.Model):
    set = models.CharField(max_length=20)

    def __str__(self):
        return self.set


class Questions(models.Model):
    question = models.CharField(max_length=200, null=True, blank=True, )
    question_sets = models.ForeignKey(Question_sets, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.question


class Options(models.Model):
    option = models.CharField(max_length=200, blank=True)
    questions = models.ForeignKey(Questions, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.option


class Answer(models.Model):
    correct_answer = models.OneToOneField(Options, on_delete=models.CASCADE)
    question = models.OneToOneField(Questions, on_delete=models.CASCADE)

    def __str__(self):
        return self.correct_answer.option

iq/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.http import JsonResponse
from .models import Questions, Question_sets, Options, Answer
# Program to generate a random number between 0 and 9

# importing the random module
import random


# Create your views here.

def home(request):
    return render(request, 'home.html')


def iq_test(request, total_correct_answer=None):
    sets = Question_sets.objects.all()
    set_item = []
    for set in sets:
        set_item.append(set.id)
    random_index = random.randint(0, len(set_item) - 1)
    print("This is random index", random_index)
    RandomQuestionSet = Question_sets.objects.filter(id=set_item[random_index]).first()
    questions = RandomQuestionSet.questions_set.all()
    single_question = []
    for question in questions:
        single_question.append(question)

    if request.method == "POST":
        answers = Answer.objects.all()
        for answer in answers:
            answers.filter()
            answer_id = answer.correct_answer.id

        for key, value in request.POST.lists():
            print(key, value)
            if key.split('-')[-1] != 'csrfmiddlewaretoken':
                qu_id = key.split('-')[-1]
                get_answer = Answer.objects.filter(question_id=qu_id,
                                                   correct_answer__option__contains=value[0])
                total_correct_answer = get_answer.count()
                if total_correct_answer == None:
                    return redirect('/')
                else:
                    context = {'score': total_correct_answer}
                    return render(request, 'result.html', context)
    context = {'questions': single_question, 'total_correct_answer': total_correct_answer}
    return render(request, 'test.html', context)

# def result(request):
#     return render(request, 'result.html')

templates/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
<h2></h2>

<div class="container">
    <div class="test-wrapper d-flex align-items-center justify-content-center flex-column" style="height: 100vh">
        <h2 class="">Start a Test : </h2>
        <a href="{% url 'test' %}" class="btn btn-primary mt-5" id="btnStart" type="button" value="Start"
           onclick="printDuration();">Start Test</a>
        <button class="btn btn-primary" id="btnStart" type="button" value="Start"
                onclick="printDuration();">Start time
        </button>
        <p id="para">0</p>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

<script type="text/javascript">
    var check = null;

    function printDuration() {
        window.location = "{% url 'test' %}";
        if (check == null) {
            var cnt = 0;

            check = setInterval(function () {
                cnt += 1;
                document.getElementById("para").innerHTML = cnt;
            }, 1000);
        }
    }

    function stop() {
        clearInterval(check);
        check = null;
        document.getElementById("para").innerHTML = '0';
    }

    console.log("Time counting... ... ...")
</script>

</body>
</html>

templates/result.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
<h2></h2>

<div class="container">
    <div class="test-wrapper d-flex align-items-center justify-content-center flex-column" style="height: 100vh">
        <h2 class="">Your Total Score: {{ score }}</h2>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

templates/test.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {#    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>#}
</head>
<body>

<div class="container">
    <div class="test-question-wrapper mt-5">
        <h2 class="pb-5">Welcome to test page</h2>
        <p id="para">0</p>
        {#        <div class="sets-wrapper">#}
        {#            <h4>Please select a set :</h4>#}
        {#            <select name="" id="set">#}
        {#                {% for set in sets %}#}
        {#                    <option value="">{{ set }}</option>#}
        {#                {% endfor %}#}
        {#            </select>#}
        {#        </div>#}
        <form method="post">
            {% csrf_token %}
            {% for question in questions %}
                <div class="test-questions mt-5" id="display_questions">
                    <p>{{ question.question }}</p>
                    {% for option in question.options_set.all %}
                        <input type="radio" name="option-{{ question.id }}" id="{{ option.id }}" value="{{ option }}">
                        <label for="">{{ option }}</label><br>
                    {% endfor %}
                </div>
            {% endfor %}
            <input type="submit" class="btn btn-primary mt-5" value="Submit your Answers">
        </form>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
{#<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>#}


<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

{#<script>#}
{#    $(document).ready(function () {#}
{#        setInterval(function () {#}
{#            $.ajax({#}
{#                type: 'GET',#}
{#                url: "{% url 'api' %}",#}
{#                success: function (response) {#}
{#                    $("#display_questions").empty();#}
{#                    for (var question in response.questions) {#}
{#                        var temp = "<p>" + response.questions[question].question + "</p>";#}
{#                        $("#display_questions").append(temp);#}
{#                    }#}
{#                },#}
{#                error: function () {#}
{#                    console.log('fail');#}
{#                    alert('An Error Occured');#}
{#                }#}
{#            });#}
{#        }, 1000);#}
{#    });#}
{#</script>#}
{##}
{#Select2#}
{##}
{#<script>#}
{#    // In your Javascript (external .js resource or <script> tag)#}
{#    $(document).ready(function () {#}
{#        $('#set').select2();#}
{#    });#}
{#</script>#}


<script type="text/javascript">
    var check = null;

    function printDuration() {
        if (check == null) {
            var cnt = 0;

            check = setInterval(function () {
                cnt += 1;
                document.getElementById("para").innerHTML = cnt;
            }, 1000);
        }
    }

    function stop() {
        clearInterval(check);
        check = null;
        document.getElementById("para").innerHTML = '0';
    }

    console.log("Time counting... ... ...")
</script>


</body>
</html>